using ConfigContraband.Tests.Infrastructure;

namespace ConfigContraband.Tests;

public sealed partial class ConfigContrabandAnalyzerTests
{
    [Fact]
    public void CI_enforces_the_showcase_diagnostic_contract()
    {
        var repositoryRoot = Path.GetFullPath(
            Path.Combine(AppContext.BaseDirectory, "../../../../.."));
        var workflow = File.ReadAllText(
            Path.Combine(repositoryRoot, ".github", "workflows", "ci.yml"));
        var verifier = Path.Combine(repositoryRoot, "scripts", "verify-showcase.sh");

        Assert.Contains("bash scripts/verify-showcase.sh", workflow, StringComparison.Ordinal);
        Assert.True(File.Exists(verifier), "The CI showcase verifier script must exist.");

        var verifierContents = File.ReadAllText(verifier);
        Assert.Contains("-tl:off", verifierContents, StringComparison.Ordinal);
        foreach (var ruleId in Enumerable.Range(1, 9).Select(number => $"CFG{number:000}"))
        {
            Assert.Contains(ruleId, verifierContents, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void Packaged_analyzer_references_net8_compatible_roslyn()
    {
        var supportedRoslynVersion = new Version(4, 8, 0, 0);
        var packagedAssemblies = new[]
        {
            typeof(ConfigContrabandAnalyzer).Assembly,
            typeof(ConfigurationSnapshot).Assembly,
        };

        var roslynReferences = packagedAssemblies
            .SelectMany(assembly => assembly.GetReferencedAssemblies())
            .Where(reference => reference.Name?.StartsWith("Microsoft.CodeAnalysis", StringComparison.Ordinal) == true)
            .ToArray();

        Assert.NotEmpty(roslynReferences);

        var mismatchedReferences = roslynReferences
            .Where(reference => reference.Version != supportedRoslynVersion)
            .Select(reference => $"{reference.Name}, Version={reference.Version}")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(reference => reference)
            .ToArray();

        Assert.True(
            mismatchedReferences.Length == 0,
            $"The shipped analyzer assemblies must reference the exact .NET 8 / Visual Studio 17.8 "
            + $"Roslyn baseline {supportedRoslynVersion}. Mismatches: {string.Join(", ", mismatchedReferences)}");
    }

    [Fact]
    public async Task Analyzer_ignores_generated_code()
    {
        var source = """
            // <auto-generated/>
            using System.ComponentModel.DataAnnotations;
            using Microsoft.Extensions.DependencyInjection;

            public sealed class Startup
            {
                public void Configure(IServiceCollection services)
                {
                    services.AddOptions<StripeOptions>()
                        .BindConfiguration("Strpie")
                        .ValidateDataAnnotations();
                }
            }

            public sealed class StripeOptions
            {
                [Required]
                public string ApiKey { get; set; } = "";
            }
            """;

        await Verifier.VerifyAnalyzerAsync(
            source,
            ("appsettings.json", """
            {
              "Stripe": {
                "ApiKey": "secret"
              }
            }
            """));
    }

    [Fact]
    public async Task Analyzer_ignores_generated_file_names()
    {
        var source = """
            using System.ComponentModel.DataAnnotations;
            using Microsoft.Extensions.DependencyInjection;

            public sealed class Startup
            {
                public void Configure(IServiceCollection services)
                {
                    services.AddOptions<StripeOptions>()
                        .BindConfiguration("Strpie")
                        .ValidateDataAnnotations();
                }
            }

            public sealed class StripeOptions
            {
                [Required]
                public string ApiKey { get; set; } = "";
            }
            """;

        await Verifier.VerifyAnalyzerAsync(
            [("GeneratedOptions.g.cs", source)],
            ("appsettings.json", """
            {
              "Stripe": {
                "ApiKey": "secret"
              }
            }
            """));
    }

    [Fact]
    public void Runtime_validation_rejects_default_struct_that_skips_member_initializer()
    {
        var value = default(RuntimeDefaultStructOptions);
        object instance = value;
        var results = new List<System.ComponentModel.DataAnnotations.ValidationResult>();

        var isValid = System.ComponentModel.DataAnnotations.Validator.TryValidateObject(
            instance,
            new System.ComponentModel.DataAnnotations.ValidationContext(instance),
            results,
            validateAllProperties: true);

        Assert.False(isValid);
        Assert.Null(value.ConnectionString);
    }

    [Fact]
    public void Required_attribute_accepts_every_non_null_array_initializer_shape()
    {
        var defaults = new RuntimeRequiredArrayDefaults();
        var required = new System.ComponentModel.DataAnnotations.RequiredAttribute();

        Assert.All(
            new[]
            {
                defaults.CollectionExpression,
                defaults.ImplicitArray,
                defaults.ExplicitSizedArray,
                defaults.ExplicitArray,
            },
            value =>
            {
                Assert.NotNull(value);
                Assert.True(required.IsValid(value));
            });
    }

#pragma warning disable CA1825 // Exact new string[0] syntax is part of the runtime-parity matrix.
    private sealed class RuntimeRequiredArrayDefaults
    {
        public string[] CollectionExpression { get; } = [];

        public string[] ImplicitArray { get; } = new[] { "configured" };

        public string[] ExplicitSizedArray { get; } = new string[0];

        public string[] ExplicitArray { get; } = new string[] { "configured" };
    }
#pragma warning restore CA1825
}
