using ConfigContraband.Tests.Infrastructure;

namespace ConfigContraband.Tests;

public sealed partial class ConfigContrabandAnalyzerTests
{
    [Fact]
    public void Packaged_analyzer_references_net8_compatible_roslyn()
    {
        var supportedRoslynVersion = new Version(4, 8, 0, 0);
        var packagedAssemblies = new[]
        {
            typeof(ConfigContrabandAnalyzer).Assembly,
            typeof(ConfigurationSnapshot).Assembly,
        };

        var roslynReferences = packagedAssemblies
            .SelectMany(assembly => assembly.GetReferencedAssemblies())
            .Where(reference => reference.Name?.StartsWith("Microsoft.CodeAnalysis", StringComparison.Ordinal) == true)
            .ToArray();

        Assert.NotEmpty(roslynReferences);

        var mismatchedReferences = roslynReferences
            .Where(reference => reference.Version != supportedRoslynVersion)
            .Select(reference => $"{reference.Name}, Version={reference.Version}")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(reference => reference)
            .ToArray();

        Assert.True(
            mismatchedReferences.Length == 0,
            $"The shipped analyzer assemblies must reference the exact .NET 8 / Visual Studio 17.8 "
            + $"Roslyn baseline {supportedRoslynVersion}. Mismatches: {string.Join(", ", mismatchedReferences)}");
    }

    [Fact]
    public async Task Analyzer_ignores_generated_code()
    {
        var source = """
            // <auto-generated/>
            using System.ComponentModel.DataAnnotations;
            using Microsoft.Extensions.DependencyInjection;

            public sealed class Startup
            {
                public void Configure(IServiceCollection services)
                {
                    services.AddOptions<StripeOptions>()
                        .BindConfiguration("Strpie")
                        .ValidateDataAnnotations();
                }
            }

            public sealed class StripeOptions
            {
                [Required]
                public string ApiKey { get; set; } = "";
            }
            """;

        await Verifier.VerifyAnalyzerAsync(
            source,
            ("appsettings.json", """
            {
              "Stripe": {
                "ApiKey": "secret"
              }
            }
            """));
    }

    [Fact]
    public async Task Analyzer_ignores_generated_file_names()
    {
        var source = """
            using System.ComponentModel.DataAnnotations;
            using Microsoft.Extensions.DependencyInjection;

            public sealed class Startup
            {
                public void Configure(IServiceCollection services)
                {
                    services.AddOptions<StripeOptions>()
                        .BindConfiguration("Strpie")
                        .ValidateDataAnnotations();
                }
            }

            public sealed class StripeOptions
            {
                [Required]
                public string ApiKey { get; set; } = "";
            }
            """;

        await Verifier.VerifyAnalyzerAsync(
            [("GeneratedOptions.g.cs", source)],
            ("appsettings.json", """
            {
              "Stripe": {
                "ApiKey": "secret"
              }
            }
            """));
    }

    [Fact]
    public void Runtime_validation_rejects_default_struct_that_skips_member_initializer()
    {
        var value = default(RuntimeDefaultStructOptions);
        object instance = value;
        var results = new List<System.ComponentModel.DataAnnotations.ValidationResult>();

        var isValid = System.ComponentModel.DataAnnotations.Validator.TryValidateObject(
            instance,
            new System.ComponentModel.DataAnnotations.ValidationContext(instance),
            results,
            validateAllProperties: true);

        Assert.False(isValid);
        Assert.Null(value.ConnectionString);
    }
}
