using ConfigContraband.Tests.Infrastructure;

namespace ConfigContraband.Tests;

public sealed partial class ConfigContrabandAnalyzerTests
{

    [Fact]
    public async Task Analyzer_ignores_generated_code()
    {
        var source = """
            // <auto-generated/>
            using System.ComponentModel.DataAnnotations;
            using Microsoft.Extensions.DependencyInjection;

            public sealed class Startup
            {
                public void Configure(IServiceCollection services)
                {
                    services.AddOptions<StripeOptions>()
                        .BindConfiguration("Strpie")
                        .ValidateDataAnnotations();
                }
            }

            public sealed class StripeOptions
            {
                [Required]
                public string ApiKey { get; set; } = "";
            }
            """;

        await Verifier.VerifyAnalyzerAsync(
            source,
            ("appsettings.json", """
            {
              "Stripe": {
                "ApiKey": "secret"
              }
            }
            """));
    }

    [Fact]
    public async Task Analyzer_ignores_generated_file_names()
    {
        var source = """
            using System.ComponentModel.DataAnnotations;
            using Microsoft.Extensions.DependencyInjection;

            public sealed class Startup
            {
                public void Configure(IServiceCollection services)
                {
                    services.AddOptions<StripeOptions>()
                        .BindConfiguration("Strpie")
                        .ValidateDataAnnotations();
                }
            }

            public sealed class StripeOptions
            {
                [Required]
                public string ApiKey { get; set; } = "";
            }
            """;

        await Verifier.VerifyAnalyzerAsync(
            [("GeneratedOptions.g.cs", source)],
            ("appsettings.json", """
            {
              "Stripe": {
                "ApiKey": "secret"
              }
            }
            """));
    }

    [Fact]
    public void Runtime_validation_rejects_default_struct_that_skips_member_initializer()
    {
        var value = default(RuntimeDefaultStructOptions);
        object instance = value;
        var results = new List<System.ComponentModel.DataAnnotations.ValidationResult>();

        var isValid = System.ComponentModel.DataAnnotations.Validator.TryValidateObject(
            instance,
            new System.ComponentModel.DataAnnotations.ValidationContext(instance),
            results,
            validateAllProperties: true);

        Assert.False(isValid);
        Assert.Null(value.ConnectionString);
    }
}
